import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import db from '../Firebase/clientApp.ts'
// import firebase from 'firebase/app'
import { collection, getDocs } from 'firebase/firestore'
// import { useCollection } from 'react-firebase-hooks/firestore'

export default function Home({ docList }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <h2>data pulled from Firebase dummy collection</h2>
        <h3>obviously.. still a lot of work to do here :P</h3>
        <div>
          <p>id: {docList[0].id}</p>
          <p>title: {docList[0].title}</p>
          <p>body: {docList[0].body}</p>
        </div>

      </main>
    </div>
  )
}

// yanked from https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering
export async function getServerSideProps(context) {
  const dummyCol = collection(db, 'dummy')
  const dummySnapshot = await getDocs(dummyCol)
  // console.log(dummySnapshot.docs)
  const docList = dummySnapshot.docs.map((doc) => {
    var arr = doc.data()
    arr.id = doc.id
    return arr
  });
  console.log(docList)
  return {
    
    // will be passed to the page component as props
    props: {
      docList,
    },
  }
}
